title: CR's Homepage
logo: /assets/img/self1.jpg
description: A personal blog about technology and life.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
author: Chenrun Wang
email: 1282713208@qq.com
