title: Chenrun's Homepage
logo: /assets/img/logo.png
description: A personal blog about technology and life.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
author: Chenrun Wang
email: 1282713208@qq.com
